# Generated by Django 3.2.2 on 2021-12-20 23:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rendimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Importador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=255)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rendimiento.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Exportador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=255)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rendimiento.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transporte', models.CharField(max_length=255)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('exportador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rendimiento.exportador')),
                ('importador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rendimiento.importador')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rendimiento.producto')),
            ],
        ),
    ]
