# Generated by Django 3.2.2 on 2021-12-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendimiento', '0002_detalle_exportador_importador_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='cantidad',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
